apiVersion: v1
kind: Pod
metadata:
    name: sample-pod
    labels:
       zone: prod
       version: v1
spec:
   containers:
   - name: myapp
     image: sirishadevops/deploy:v1
     ports:
     - containerPort: 80
